name: CI-CD Pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: List files (debug)
        run: ls -la
      
      - name: Build Docker
        run: docker build -t app .
        # Si el Dockerfile está en ./ActDocker/, usa: docker build -t app ./ActDocker
      
      - name: Run container
        run: docker run -d -p 8080:80 app